# Application Properties
spring:
  application:
    name: User Registration
  # Jpa Properties
  datasource:
    url: jdbc:mysql://localhost:3306/userregistration
    username: root
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  # Liquibase properties
  liquibase:
    enabled: false

## Server Properties
server:
  port: 8081

